url: https://reggieboyYEAH.github.io

# Site settings
brand: "{reggiepangilinan}"
title:  Reggie Pangilinan Blog + Portfolio
email: reggiepangilinan@gmail.com
description: "Reggie Pangilinan is a Full-Stack Developer / Consultant from Makati CIty, Philippines"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000
  secondary: 000
  secondary-dark: 000

# Contact Info
author: "Reggie Pangilinan"
position: "Head of Development Dept / Full Stack Engineer"
company: "BizBox Inc"
# Postal address (add as many lines as necessary)
address:
  - line: 1103 ANTEL 2000 Corporate Centre
  - line: 121 Valero St. Salcedo Village
  - line: Makati City, Philippines




# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/reggiepangilinan
  - title: github
    url: http://github.com/reggieboyYEAH
  - title: linkedin
    url: https://au.linkedin.com/in/reggie-pangilinan-60525414

# Build settings
markdown: kramdown
permalink: pretty