url: https://reggieboyYEAH.github.io

# Site settings
title: Reggie Pangilinan Blog + Portfolio
email: reggiepangilinan@gmail.com
description: "Reggie Pangilinan is a Full-Stack Developer / Consultant from Makati CIty, Philippines"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000
  secondary: 000
  secondary-dark: 000


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty